name: amit
description: "A new Flutter project."
publish_to: 'none'
 version: 1.0.1+6
# version: 1.0.2+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  audioplayers: ^6.0.0
  wakelock: ^0.6.2
  assets_audio_player: ^3.0.8
  internet_connection_checker: ^1.0.0+1
  native_device_orientation: ^2.0.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  video_player: ^2.8.6
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  native_shared_preferences: ^2.0.10
  shared_preference_app_group: ^1.1.1
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mexicano.jpeg"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/balaha.jpeg
      - assets/balaha1.jpeg      
      - assets/balahax.jpeg    
      - assets/mexicano.jpeg
      - assets/balahaz.mp3    

  fonts:
     - family: Aclonica
       fonts:
         - asset: assets/fonts/Aclonica-Regular.ttf